import { Router, Request, Response } from 'express';
import { generateXsltFromPrompt } from '../services/ai.service';

const router = Router();

/**
 * POST /api/ai/chat
 * Body: { prompt: string; xslt: string; xml: string }
 * Returns: { success: true, xslt: string, message: string }
 */
router.post('/chat', async (req: Request, res: Response) => {
  const { prompt, xslt, xml } = req.body as { prompt?: string; xslt?: string; xml?: string };

  if (!prompt || !xslt || !xml) {
    res.status(400).json({ success: false, error: 'prompt, xslt, and xml are required' });
    return;
  }

  try {
    const result = await generateXsltFromPrompt(prompt, xslt, xml);
    res.json({ success: true, xslt: result.xslt, message: result.message });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message || 'AI generation failed' });
  }
});

// XSLT/XSL-FO snippet library for AI suggestions
const XSLT_SNIPPETS: Record<string, string> = {
  'basic-template': `<xsl:template match="/">
  <fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
    <fo:layout-master-set>
      <fo:simple-page-master master-name="A4"
        page-height="29.7cm" page-width="21cm"
        margin="2cm">
        <fo:region-body/>
      </fo:simple-page-master>
    </fo:layout-master-set>
    <fo:page-sequence master-reference="A4">
      <fo:flow flow-name="xsl-region-body">
        <fo:block font-size="12pt">
          <xsl:value-of select="."/>
        </fo:block>
      </fo:flow>
    </fo:page-sequence>
  </fo:root>
</xsl:template>`,

  'table': `<fo:table table-layout="fixed" width="100%">
  <fo:table-column column-width="proportional-column-width(1)"/>
  <fo:table-column column-width="proportional-column-width(2)"/>
  <fo:table-header>
    <fo:table-row background-color="#003366">
      <fo:table-cell padding="4pt">
        <fo:block color="white" font-weight="bold">Column 1</fo:block>
      </fo:table-cell>
      <fo:table-cell padding="4pt">
        <fo:block color="white" font-weight="bold">Column 2</fo:block>
      </fo:table-cell>
    </fo:table-row>
  </fo:table-header>
  <fo:table-body>
    <xsl:for-each select="items/item">
      <fo:table-row>
        <fo:table-cell padding="4pt">
          <fo:block><xsl:value-of select="field1"/></fo:block>
        </fo:table-cell>
        <fo:table-cell padding="4pt">
          <fo:block><xsl:value-of select="field2"/></fo:block>
        </fo:table-cell>
      </fo:table-row>
    </xsl:for-each>
  </fo:table-body>
</fo:table>`,

  'conditional': `<xsl:choose>
  <xsl:when test="@type = 'HU'">
    <fo:block border="1pt solid #003366" padding="6pt" margin-bottom="4pt">
      <fo:block font-weight="bold" color="#003366">
        Handling Unit: <xsl:value-of select="@id"/>
      </fo:block>
      <xsl:apply-templates select="children/HU"/>
    </fo:block>
  </xsl:when>
  <xsl:otherwise>
    <fo:block>
      <xsl:value-of select="."/>
    </fo:block>
  </xsl:otherwise>
</xsl:choose>`,

  'for-each': `<xsl:for-each select="items/item">
  <fo:block margin-bottom="4pt">
    <xsl:value-of select="."/>
  </fo:block>
</xsl:for-each>`,

  'header-footer': `<fo:static-content flow-name="xsl-region-before">
  <fo:block text-align="center" font-size="8pt" color="#666">
    Document Header - Page <fo:page-number/>
  </fo:block>
</fo:static-content>
<fo:static-content flow-name="xsl-region-after">
  <fo:block text-align="center" font-size="8pt" color="#666">
    Confidential - Generated by Ariba PDF Tool
  </fo:block>
</fo:static-content>`,

  'box': `<fo:block border="1pt solid #cccccc" padding="8pt" margin="4pt"
  background-color="#f9f9f9" border-radius="3pt">
  <fo:block font-weight="bold" font-size="10pt" color="#003366">
    Section Title
  </fo:block>
  <fo:block font-size="9pt" margin-top="4pt">
    Content here
  </fo:block>
</fo:block>`,
};

/**
 * POST /api/ai/suggest
 * Body: { context: string, cursorPosition?: number }
 * Returns: { suggestion: string, label: string }[]
 */
router.post('/suggest', (_req: Request, res: Response) => {
  const { context } = _req.body as { context?: string; cursorPosition?: number };

  if (!context) {
    res.status(400).json({ success: false, error: 'context is required' });
    return;
  }

  const lower = context.toLowerCase();
  const suggestions: { label: string; snippet: string; description: string }[] = [];

  // Match suggestions based on keywords in context
  if (lower.includes('for-each') || lower.includes('foreach') || lower.includes('loop')) {
    suggestions.push({
      label: 'for-each loop',
      snippet: XSLT_SNIPPETS['for-each'],
      description: 'Iterate over XML nodes with xsl:for-each',
    });
  }
  if (lower.includes('table') || lower.includes('row') || lower.includes('column')) {
    suggestions.push({
      label: 'XSL-FO Table',
      snippet: XSLT_SNIPPETS['table'],
      description: 'Generate a styled table from XML data',
    });
  }
  if (lower.includes('if') || lower.includes('when') || lower.includes('conditional') || lower.includes('choose')) {
    suggestions.push({
      label: 'Conditional block (xsl:choose)',
      snippet: XSLT_SNIPPETS['conditional'],
      description: 'Add conditional rendering with xsl:choose/when',
    });
  }
  if (lower.includes('hu') || lower.includes('handling unit') || lower.includes('nested')) {
    suggestions.push({
      label: 'Handling Unit (HU) nested block',
      snippet: XSLT_SNIPPETS['conditional'],
      description: 'Display nested HU hierarchies with conditional logic',
    });
  }
  if (lower.includes('header') || lower.includes('footer') || lower.includes('page')) {
    suggestions.push({
      label: 'Header and Footer',
      snippet: XSLT_SNIPPETS['header-footer'],
      description: 'Add page header and footer regions',
    });
  }
  if (lower.includes('box') || lower.includes('block') || lower.includes('border') || lower.includes('section')) {
    suggestions.push({
      label: 'Styled box section',
      snippet: XSLT_SNIPPETS['box'],
      description: 'Add a styled bordered section block',
    });
  }
  if (lower.includes('template') || lower.includes('root') || lower.includes('start') || lower.includes('basic')) {
    suggestions.push({
      label: 'Basic XSL-FO template',
      snippet: XSLT_SNIPPETS['basic-template'],
      description: 'Complete basic XSLT template with XSL-FO output',
    });
  }

  // If no specific matches, return all common snippets
  if (suggestions.length === 0) {
    suggestions.push(
      { label: 'Basic XSL-FO template', snippet: XSLT_SNIPPETS['basic-template'], description: 'Complete XSLT/XSL-FO template scaffold' },
      { label: 'for-each loop', snippet: XSLT_SNIPPETS['for-each'], description: 'Iterate over XML nodes' },
      { label: 'XSL-FO Table', snippet: XSLT_SNIPPETS['table'], description: 'Styled data table' },
    );
  }

  res.json({ success: true, suggestions: suggestions.slice(0, 3) });
});

/**
 * GET /api/ai/samples
 * Returns sample XML documents for different document types
 */
router.get('/samples', (_req: Request, res: Response) => {
  const samples = {
    po: `<?xml version="1.0" encoding="UTF-8"?>
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  orderID="PO-2024-001" orderDate="2024-01-15" currency="EUR">
  <Supplier>
    <Name>Acme Supplies GmbH</Name>
    <Address>123 Industrial Blvd, Munich, Germany</Address>
  </Supplier>
  <Buyer>
    <Name>SAP Ariba Demo Corp</Name>
    <Address>456 Enterprise Ave, Walldorf, Germany</Address>
  </Buyer>
  <LineItems>
    <LineItem lineNumber="1">
      <Description>Industrial Widget Type A</Description>
      <Quantity unit="EA">100</Quantity>
      <UnitPrice>15.50</UnitPrice>
      <TotalPrice>1550.00</TotalPrice>
    </LineItem>
    <LineItem lineNumber="2">
      <Description>Precision Gear Assembly</Description>
      <Quantity unit="EA">25</Quantity>
      <UnitPrice>89.99</UnitPrice>
      <TotalPrice>2249.75</TotalPrice>
    </LineItem>
  </LineItems>
  <TotalAmount>3799.75</TotalAmount>
</PurchaseOrder>`,

    asn: `<?xml version="1.0" encoding="UTF-8"?>
<AdvanceShipNotice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  asnID="ASN-2024-055" shipDate="2024-01-20" deliveryDate="2024-01-23">
  <Shipper>
    <Name>Acme Supplies GmbH</Name>
    <TrackingNumber>DHL-9876543210</TrackingNumber>
    <Carrier>DHL Express</Carrier>
  </Shipper>
  <ShipTo>
    <Name>SAP Ariba Demo Corp - Warehouse A</Name>
    <Address>456 Enterprise Ave, Walldorf, Germany</Address>
  </ShipTo>
  <HandlingUnits>
    <HandlingUnit huID="HU-001" type="Pallet">
      <Weight unit="KG">45.2</Weight>
      <Dimensions unit="CM">120x80x100</Dimensions>
      <Contents>
        <Item itemID="WIDGET-A" quantity="100" uom="EA"/>
      </Contents>
    </HandlingUnit>
    <HandlingUnit huID="HU-002" type="Box">
      <Weight unit="KG">12.8</Weight>
      <Dimensions unit="CM">60x40x40</Dimensions>
      <Contents>
        <Item itemID="GEAR-ASM" quantity="25" uom="EA"/>
      </Contents>
    </HandlingUnit>
  </HandlingUnits>
</AdvanceShipNotice>`,

    hu: `<?xml version="1.0" encoding="UTF-8"?>
<HandlingUnitHierarchy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  shipmentID="SHIP-2024-099" warehouseID="WH-GERMANY-01">
  <HandlingUnit huID="PALLET-001" type="Pallet" level="1">
    <Weight unit="KG">80.5</Weight>
    <Dimensions unit="CM">120x80x150</Dimensions>
    <HandlingUnit huID="BOX-001-A" type="Box" level="2">
      <Weight unit="KG">15.2</Weight>
      <HandlingUnit huID="INNER-001" type="InnerPack" level="3">
        <Weight unit="KG">3.1</Weight>
        <Item itemID="PART-X001" description="Micro Component" quantity="50" uom="PCS"/>
      </HandlingUnit>
      <HandlingUnit huID="INNER-002" type="InnerPack" level="3">
        <Weight unit="KG">4.5</Weight>
        <Item itemID="PART-X002" description="Sensor Module" quantity="20" uom="PCS"/>
      </HandlingUnit>
    </HandlingUnit>
    <HandlingUnit huID="BOX-001-B" type="Box" level="2">
      <Weight unit="KG">22.0</Weight>
      <Item itemID="PART-Y003" description="Assembly Kit" quantity="10" uom="SET"/>
    </HandlingUnit>
  </HandlingUnit>
</HandlingUnitHierarchy>`,
  };

  res.json({ success: true, samples });
});

export default router;
